/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PandaRestaurant.View.Form.Customer_Form;
public class AboutUs_Form extends javax.swing.JPanel {

    /**
     * Creates new form AboutUs_Form
     */
    public AboutUs_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new PandaRestaurant.View.Swing.PanelRound();
        img = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        wel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        footer = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        header1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 222, 222));

        panelRound1.setBackground(new java.awt.Color(247, 247, 247));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/aboutus.jpg"))); // NOI18N

        header.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        header.setForeground(new java.awt.Color(147, 5, 13));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("ABOUT US");

        wel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        wel.setForeground(new java.awt.Color(63, 63, 63));
        wel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wel.setText("<html>      <i style=\"color:#93050D;font-size:16px;\">WELCOME TO PANDA FOOD</i> </html> ");

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt.setEditable(false);
        txt.setBackground(new java.awt.Color(255, 255, 255));
        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt.setForeground(new java.awt.Color(89, 89, 89));
        txt.setLineWrap(true);
        txt.setRows(5);
        txt.setText("Bước vào nhà hàng của Panda, bạn sẽ ngay lập tức bị cuốn hút bởi không gian thanh lịch và sang trọng. Với thiết kế kiến trúc tinh tế, từng chi tiết nội thất được chăm chút kỹ lưỡng, mang đậm phong cách cổ điển nhưng không kém phần hiện đại. Đó là sự kết hợp tuyệt vời giữa nghệ thuật và kiến trúc, tạo nên một không gian đẳng cấp và lịch lãm.\n\nĐội ngũ đầu bếp của Panda không chỉ là những người nấu ăn, mà là những nghệ nhân thực sự. Họ tạo ra những món ăn như những tác phẩm nghệ thuật, kết hợp các hương vị một cách khéo léo và tinh tế để mang đến cho thực khách trải nghiệm ẩm thực khó quên. Nguyên liệu Panda sử dụng luôn tươi ngon và cao cấp, kết hợp với sự sáng tạo và kỹ thuật chế biến đỉnh cao, để mang đến những món ăn truyền thống với phong cách hiện đại độc đáo.\n\nNhà hàng Panda là nơi lý tưởng để bạn cùng gia đình và bạn bè tụ họp.Panda luôn tạo ra một không gian riêng tư và thoải mái, với ánh sáng dịu nhẹ và không gian yên tĩnh, giúp thực khách có thể tận hưởng những bữa ăn thượng hạng trong không gian ấm cúng.\n\nĐội ngũ nhân viên phục vụ chuyên nghiệp và tận tâm của Panda luôn sẵn sàng phục vụ, đảm bảo mỗi khách hàng đều được chăm sóc chu đáo. Panda với mục tiêu không chỉ phục vụ món ăn ngon, mà còn mang đến những trải nghiệm ẩm thực vượt ngoài mong đợi.\n\nHãy đến và trải nghiệm không gian thanh lịch và tinh tế của nhà hàng Panda. Panda Food Restaurant cam kết mang đến cho quý khách trải nghiệm ẩm thực đẳng cấp, tạo nên những kỷ niệm đáng nhớ qua từng bữa ăn.");
        txt.setWrapStyleWord(true);
        txt.setBorder(null);
        txt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt.setFocusable(false);
        txt.setRequestFocusEnabled(false);
        txt.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(txt);

        footer.setBackground(new java.awt.Color(255, 255, 255));
        footer.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        footer.setForeground(new java.awt.Color(0, 51, 51));
        footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footer.setText("Since : 2024 - Co-founder by Panda Team");

        jSeparator1.setBackground(new java.awt.Color(76, 76, 76));

        header1.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header1.setText("Crafted with Love, Savored with Joy.");
        header1.setToolTipText("");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(wel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)))
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(header1)
                .addGap(18, 18, 18)
                .addComponent(wel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 756, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel footer;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel img;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private PandaRestaurant.View.Swing.PanelRound panelRound1;
    private javax.swing.JTextArea txt;
    private javax.swing.JLabel wel;
    // End of variables declaration//GEN-END:variables
}
